ENG-2070 Add cypress tests for groups
entando/app-builder pull request #1036
Opened 2021-03-30 09:57 UTC by raxkaynan

2021-03-30 09:57 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **raxkaynan**

If they are not already assigned, you can assign the PR to them by writing `/assign @raxkaynan` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["raxkaynan"]} -->

2021-04-05 15:19 UTC, avdev4j requested changes

2021-04-05 15:19 UTC, avdev4j commented on test/cypress/integration/groups.spec.js
> +    cy.getByTestId('groups-table').should('be.visible');
move the id into a constant file

2021-04-05 15:19 UTC, avdev4j commented on test/cypress/support/command/group-command.js
> +  cy.getByTestId('group-delete-action').filter(':visible').click();
move the id into a constant file

2021-04-19 13:17 UTC, gidesan commented
@raxkaynan anything that blocks you here?

2021-04-20 08:44 UTC, alepintus approved these changes
Looks good

2021-04-20 08:44 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/entando/app-builder/pull/1036#pullrequestreview-639675349" title="Approved">alepintus</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)~~ [alepintus]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-04-20 08:44 UTC, merged