ENG-2687: validate Page title fields even when they are on a hidden tab
entando/app-builder pull request #1143
Opened 2021-10-18 13:00 UTC by gReis89

mountOnEnter and unmountOnExit props were keeping the unselected tabs unmounted, and unmounted component doesn't validate itself through redux-forms. Removing these props makes the fields hidden but mounted, so required fields on hidden tabs will start to validate as we want.

2021-10-18 13:26 UTC, raxkaynan requested changes
After doing a quick test, I found one problem: the page can't be saved unless you fill in the title for every other language. AFAIK, you should be able to save the page if you're in the default language tab and have filled in the required fields.

2021-10-18 13:36 UTC, gReis89 commented
@raxkaynan good catch! So it doesn't make more sense making the other language fields optional?

2021-10-18 14:50 UTC, gReis89 commented
Added a logic to dynamically mark the Title field as `required` accordingly to whether or not the users have accessed another lang tab, as per @nicpuddu suggestion.

2021-10-19 07:06 UTC, raxkaynan requested changes
The new changes seem to prevent the user from saving the page if another language tab has been "touched" but not filled out, even when the user goes back to the default tab. The previous behavior was that the save button is disabled if the "active" tab is a non-default language tab and its required title is empty.

@nicpuddu Is the newly introduced logic the correct behavior?

2021-10-19 07:06 UTC, raxkaynan commented on src/ui/pages/common/SeoInfo.js
> +    return false;
This produces a console warning stating "Invalid prop supplied to Field". It should probably return an empty array here instead of `false`.

2021-10-19 10:13 UTC, gReis89 commented
This is the agreed behaviour @raxkaynan 
once users acknowledge a tab it become required and users must fill it before proceed. The autocomplete feature will only be applied if users doesn't touch the tab

2021-10-19 10:14 UTC, gReis89 commented on src/ui/pages/common/SeoInfo.js
> +    return false;
fixed!

2021-10-19 12:18 UTC, raxkaynan approved these changes

2021-10-19 12:24 UTC, merged