ENG-2717: fixing modal and content edit page
entando/app-builder pull request #1159
Opened 2021-10-26 11:41 UTC by gReis89

2021-10-26 11:48 UTC, jeffgo10 requested changes
just one question...

2021-10-26 11:48 UTC, jeffgo10 commented on src/state/edit-content/actions.js
> +import _, { pickBy, isObject, cloneDeep } from 'lodash';
is there a reason you used `_` instead putting `isEmpty` inside the bracket (e.g. `{ isEmpty, pickBy, etc... }`?

2021-10-26 15:39 UTC, gReis89 commented on src/state/edit-content/actions.js
> +import _, { pickBy, isObject, cloneDeep } from 'lodash';
ops, I did not notice we already had the import in the file, I used the IDE autocomplete feature. I'm going to change it

2021-10-27 06:22 UTC, jeffgo10 approved these changes

2021-10-27 11:08 UTC, merged