ENG-3627: create system to render MFE on content container
entando/app-builder pull request #1305
Opened 2022-05-09 20:35 UTC by gReis89

2022-05-09 20:36 UTC, gReis89 commented on src/app-init/MfeDownloadManager.js
> -  return <div>{children}</div>;
we need to wait the API response before rendering the Router, or the users will see a 404 page until we get the response

2022-05-19 08:17 UTC, Dv92 requested changes

2022-05-19 08:17 UTC, Dv92 commented on src/helpers/microfrontends.js
> +export const renderMicrofrontendWithParams = (customElement, params = {}) => {
I think you must extend `renderMicrofronted` function instead of creating a new one. The param here is optional so the implementation is basically the same and doesn't impact the places where renderMicrofronted is used. The test is missing, please add it.

2022-05-19 08:17 UTC, Dv92 commented on src/app-init/MfeDownloadManager.js
> +  const [loading, setLoading] = React.useState(true);
for consistency destruct useState

2022-05-19 08:17 UTC, Dv92 commented on src/ui/internal-page/VerticalMenuContainer.js
> +  const mfeHeaderMenu = useSelector(getMfeTargetPrimaryHeader);
for now delete the header part. For the 7.1 we don't integrate the header

2022-05-19 08:17 UTC, Dv92 commented on src/ui/app/App.js
> +          render={() => <InternalPage><MfeContainer id={mfe.id} /></InternalPage>}
I think you don't need InternalPage in this case. The view where the MFE is injected must be empty so you don't need the style of InternalPage

2022-05-19 08:17 UTC, Dv92 commented on src/ui/app/MfeContainer.js
> +export default MfeContainer;
missing the test about this component

2022-05-19 08:17 UTC, Dv92 commented on public/mocks/app-builder-menu/main.js
> +customElements.define('app-builder-menu', AppBuilderMenuMFE);
rename the directory and the component as "example-mfe-menu" for consistency

2022-05-19 08:17 UTC, Dv92 commented on public/mocks/app-builder-header/main.js
> +customElements.define('app-builder-header', AppBuilderHeaderMFE);
for the 7.1 we don't need header. You can delete this mock

2022-05-19 08:17 UTC, Dv92 commented on src/ui/internal-page/VerticalMenuContainer.js
> +    <div className="MfeContainer__left-menu-container">
for now delete this header part

2022-05-19 08:17 UTC, Dv92 commented on src/ui/internal-page/VerticalMenuContainer.js
> +  <div className="MfeContainer">
keep the className consistent with the component name. Use `MfeMenuContainer`

2022-05-19 08:17 UTC, Dv92 commented on sass/internal-page/InternalPage.scss
> +}
this style must be isolated in another file. It's not related to internal page.

2022-05-19 08:17 UTC, Dv92 commented on src/hooks/useMfe.js
> +export default useMfe;
please add the test for this hook.

2022-05-20 12:53 UTC, Dv92 commented on src/api/permissions.js
> -    useCredentials: true,
@gReis89 this should be reverted

2022-05-23 08:05 UTC, Dv92 approved these changes

2022-05-23 08:20 UTC, merged