ENG-3723: moving button out of config form
entando/app-builder pull request #1320
Opened 2022-05-24 22:57 UTC by gReis89

- creating new component with panel elements to avoid code duplication
- moving MFE config forms buttons out of panel
- fix issue with Entando header not being rendered

2022-05-25 11:51 UTC, ichalagashvili requested changes
Looks good, just minor comments

2022-05-25 11:51 UTC, ichalagashvili commented on src/ui/internal-page/VerticalMenuContainer.js
> +  // return <EntandoMenu {...props} />;
can you please delete the commented code?

2022-05-25 11:51 UTC, ichalagashvili commented on src/ui/widgets/config/WidgetConfigPage.js
> +import WidgetConfigPanel from './WidgetConfigPanel';
please use absolute import path (relative to src)

2022-05-25 12:58 UTC, ichalagashvili approved these changes, later dismissed

2022-05-25 13:22 UTC, Dv92 commented on src/ui/internal-page/VerticalMenuContainer.js
>      : <EntandoMenu {...props} />;
this code is out of PR's scope. It shouldn't be in this PR because is unrelated to the ticket.

2022-05-27 09:32 UTC, ichalagashvili approved these changes

2022-05-30 12:28 UTC, Dv92 approved these changes

2022-05-30 12:30 UTC, merged