ENG-4664 implement fetching current tenant and dynamic resource urls
entando/app-builder pull request #1457
Opened 2023-03-12 20:19 UTC by ichalagashvili

2023-03-14 11:36 UTC, Dv92 requested changes
There are some logs to delete, missing some tests and small modification on naming

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useDynamicResourceUrl.js
> +  console.log('generateUrlFromTenantAndResource', tenant, resource);
can you delete this `console.log`?

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useDynamicResourceUrl.js
> +    console.log('returning local resource', resource);
same here

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useDynamicResourceUrl.js
> +    console.log('returning remote resource', `${getDomain()}/cmsresources/${resource}`);
same here

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useDynamicResourceUrl.js
> +    console.log('returning resourceUrl', `${resourceUrl}/${resource}`);
same here

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useDynamicResourceUrl.js
> +    console.log('returning resourcePath', `${resourcePath}${resource}`);
same here

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useDynamicResourceUrl.js
> +  console.log('final output is: ', process.env.NODE_ENV === 'production' ? `${getDomain()}/cmsresources/${resource}` : localResourceUrl);
same here

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useDynamicResourceUrl.js
> +  console.log('useDynamicResourceUrl', tenant, resource);
same here

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useDynamicResourceUrl.js
> +import { useSelector } from 'react-redux';
I don't see the test for `useDynamicResourceUrl`and `generateUrlFromTenantAndResource`

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useDynamicResourceUrl.js
> +export const generateUrlFromTenantAndResource = ({ tenant, resource }) => {
The name of this function seems too long, what do you think of `generateStaticAssetsUrl`?

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useMfe.js
> +  console.log('script source is: ', tenant, asset, generateUrlFromTenantAndResource({ tenant, resource: asset }));
can you delete this `console.log`?

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useMfe.js
> +  console.log('injectAssetToDom', id, assets, tenant);
same here

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useMfe.js
> +  console.log('style source is: ', tenant, asset, generateUrlFromTenantAndResource({ tenant, resource: asset }));
same here

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useMfe.js
> +  console.log('useMfe', memoMfe, tenant, assetLoading, hasError);
same here

2023-03-14 11:36 UTC, Dv92 commented on src/hooks/useMfe.js
> +  const tenant = useSelector(selectCurrentTenant) || EMPTY_OBJECT;
why do you need a`EMPTY_OBJECT` constant?

2023-03-14 11:36 UTC, Dv92 commented on src/state/multi-tenancy/actions.js
> +  }
is missing error handling for this action

2023-03-14 11:36 UTC, Dv92 commented on src/ui/app/MfeContainer.js
> +  console.log('MfeContainer->mfeResourceBasePath', mfeResourceBasePath);
can you delete this `console.log`?

2023-03-14 11:36 UTC, Dv92 commented on src/ui/app/MfeContainer.js
> +    console.log('inside useEffect->mfeResourceBasePath', mfe.widgetName, mfeResourceBasePath, entandoWindow.epc[mfe.widgetName] || { basePath: mfeResourceBasePath });
same here

2023-03-14 11:36 UTC, Dv92 commented on src/ui/widgets/config/WidgetConfigMicrofrontend.js
> +  console.log('inside WidgetConfigMicrofrontend resources', resources);
same here

2023-03-14 11:36 UTC, Dv92 commented on src/ui/widgets/config/WidgetConfigMicrofrontend.js
> +  });
same here

2023-03-14 11:36 UTC, Dv92 commented on src/ui/widgets/config/WidgetConfigPage.js
> +      console.log('isMicrofrontendWidgetForm(widget)', isMicrofrontendWidgetForm(widget), widget);
same here

2023-03-20 10:40 UTC, Dv92 submitted a review, later dismissed
LGTM

2023-03-23 09:50 UTC, Dv92 approved these changes

2023-04-06 08:20 UTC, DMinnai approved these changes

2023-04-06 08:20 UTC, merged