ENG-4705 Implement edit registry feature and add apiKey field to registry form
entando/app-builder pull request #1460
Opened 2023-03-27 13:40 UTC by raxkaynan

2023-03-27 15:36 UTC, Dv92 commented on src/state/component-repository/hub/actions.js
> +    });
you can delete this `finally`

2023-03-27 15:36 UTC, Dv92 commented on src/ui/component-repository/components/list/HubRegistrySwitcher.js
> +  }, [dispatch]);
you don't need `useCallback` in this case, see [here](https://react.dev/reference/react/useCallback#should-you-add-usecallback-everywhere)

2023-03-28 06:34 UTC, Dv92 approved these changes, later dismissed

2023-03-28 12:58 UTC, Dv92 approved these changes, later dismissed

2023-04-06 09:44 UTC, ichalagashvili requested changes

2023-04-06 09:44 UTC, ichalagashvili commented on src/ui/component-repository/components/list/EditRegistryModal.js
> +export const mustBeUnique = (values, key) => value => (value && values && values.includes(value) ? <FormattedMessage id={`hub.newRegistry.${key}.error`} /> : undefined);
Can you use same function from `src/ui/component-repository/components/list/AddNewRegistryModal.js` ?

2023-04-07 10:23 UTC, ichalagashvili approved these changes

2023-04-11 12:52 UTC, merged