Eng 4652 update code valid
entando/app-builder pull request #1461
Opened 2023-03-28 13:41 UTC by DMinnai

2023-03-29 08:32 UTC, ichalagashvili requested changes
please fix the eslint/prettier changes.

2023-03-29 08:32 UTC, ichalagashvili commented on src/helpers/attrValidation.js
> +  ));
why do we need 2 separate validators? is not just `codeWithDash` enough?

2023-03-29 12:36 UTC, DMinnai commented on src/helpers/attrValidation.js
> +  ));
I did include 2 different validator because intl messages included are different.

2023-03-31 09:46 UTC, ichalagashvili approved these changes

2023-03-31 10:22 UTC, merged

2023-03-31 11:36 UTC, DMinnai commented on src/helpers/attrValidation.js
> +  ));
I did reopen the pull for the necessary test