ENG-4965 implement manager and scenario step one
entando/app-builder pull request #1507
Opened 2023-06-19 15:39 UTC by ichalagashvili

[ENG-4965](https://entando.myjetbrains.com/youtrack/issue/ENG-4965/implement-business-logic-to-handle-API-call-and-pick-a-scenario) and [ENG-4964](https://entando.myjetbrains.com/youtrack/issue/ENG-4964/implement-scenario-1-no-external-references)

2023-06-22 19:21 UTC, DMinnai approved these changes

2023-06-28 08:00 UTC, DMinnai requested changes

2023-06-28 08:00 UTC, DMinnai commented on src/locales/it.js
> +    'ecr.componentUninstallError': 'Message error - Is not possible to uninstall the {name} component because it is used by the following components:',
I think it should be written in italian

2023-06-28 08:00 UTC, DMinnai commented on src/locales/pt.js
> +    'ecr.componentUninstallError': 'Message error - Is not possible to uninstall the {name} component because it is used by the following components:',
and this one in PT :)

2023-07-06 10:44 UTC, ichalagashvili commented on src/locales/it.js
> +    'ecr.componentUninstallError': 'Message error - Is not possible to uninstall the {name} component because it is used by the following components:',
done

2023-07-06 10:44 UTC, ichalagashvili commented on src/locales/pt.js
> +    'ecr.componentUninstallError': 'Message error - Is not possible to uninstall the {name} component because it is used by the following components:',
done

2023-07-10 11:37 UTC, DMinnai approved these changes

2023-07-10 12:34 UTC, nicpuddu approved these changes

2023-07-14 08:26 UTC, merged