ENG-4399 profile section working with updated state
entando/app-builder pull request #1527
Opened 2023-08-01 14:19 UTC by DMinnai

2023-08-02 08:51 UTC, gp-ent approved these changes
LGTM :+1:

2023-08-15 15:02 UTC, ichalagashvili requested changes
just 2 questions

2023-08-15 15:02 UTC, ichalagashvili commented on src/ui/common/formik-field/RenderSelectInput.js
> +  hasLabel,
This file already exists no? Its called `SelectInput`

2023-08-15 15:02 UTC, ichalagashvili commented on src/ui/common/formik-field/SwitchRenderer.js
> +    </div>
Does not this already exist in formik-field dir? With different name I think

2023-09-07 10:22 UTC, ichalagashvili approved these changes

2023-09-08 07:57 UTC, merged