ENG-4407 nav bar
entando/app-builder pull request #1528
Opened 2023-08-08 16:00 UTC by ryanjpburgos

2023-08-15 14:58 UTC, ichalagashvili requested changes
just 2 functions need to be replaced from redux-form and wrapping the component with redux-form should be removed

2023-08-15 14:58 UTC, ichalagashvili commented on src/ui/widgets/config/forms/NavigationBarConfigFormContainer.js
> +  onRemoveExpression: (index) => {
`reduxForm` library should be totally removed from this file. Any functionality (e.g `arrayRemove` ) should be replaced with `formik`'s alternative, or implemented some other way if it does not exist. Main goal is to at the end of the activities to uninstall `redux-form` library once all our formik tickets are done, so thats why we need remove any reference with `redux-form`

2023-09-08 08:11 UTC, DMinnai approved these changes

2023-09-13 14:32 UTC, ichalagashvili requested changes
just one thing 🙌

2023-09-13 14:32 UTC, ichalagashvili commented on src/ui/widgets/config/forms/NavigationBarConfigFormContainer.js
> +  },
I feel a bit uneasy when we are directly modifying the `expressions` . Because `expressions` come from `values` , which comes from `formik`'s internal memory, so we are directly changing array inside the formik memory. It works yes, but in some moment it might cause some unexpected behaviour. So I would do like this for example:

```javascript
  onRemoveExpression: (index, setFieldValue, values) => {
    const { expressions } = values;
    const newExpressions = [...expressions];
    newExpressions.splice(index, 1);
    setFieldValue('expressions', newExpressions);
  }
```
same with the `onSwapExpressions`

2023-09-18 14:53 UTC, ichalagashvili approved these changes

2023-09-19 15:39 UTC, merged