formik/ENG-5162 implement widget forms with formik
entando/app-builder pull request #1559
Opened 2023-10-10 15:18 UTC by ichalagashvili

2023-10-19 12:45 UTC, ryanjpburgos commented on src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
> +          invalid={false}
is it correct to have always false?

2023-10-19 12:46 UTC, ryanjpburgos commented on src/ui/widgets/common/WidgetForm.js
> +
here you can replace the function with the utility function that we have in formikUtils

2023-10-19 12:50 UTC, ryanjpburgos requested changes

2023-10-19 12:50 UTC, ryanjpburgos commented on src/ui/widgets/common/WidgetForm.js
> +  return error;
here you can replace the function with the utility function that we have in formikUtils

2023-10-22 11:59 UTC, ichalagashvili commented on src/ui/widget-forms/publish-single-content-config/SingleContentConfigFormBody.js
> +          invalid={false}
yes it is intended like that. Good catch!

2023-10-23 07:09 UTC, ryanjpburgos approved these changes

2023-10-23 15:15 UTC, merged