Update en.js
entando/app-builder pull request #785
Opened 2020-07-21 23:15 UTC by paulhinz

2020-07-21 23:15 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **kerruba**

If they are not already assigned, you can assign the PR to them by writing `/assign @kerruba` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["kerruba"]} -->

2020-07-22 05:30 UTC, gidesan requested changes

2020-07-22 05:30 UTC, gidesan commented on src/locales/en.js
> +    'pageSettings.input.languageBroswer': 'Home page localization is selection by the requesting browser',
Hey Paul, you meant "selected"?

2020-07-23 16:33 UTC, paulhinz commented on src/locales/en.js
> +    'pageSettings.input.languageBroswer': 'Home page localization is selection by the requesting browser',
Agree   - "selected"

2020-07-27 09:08 UTC, gidesan approved these changes

2020-07-27 09:08 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/entando/app-builder/pull/785#pullrequestreview-455606075" title="Approved">gidesan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)~~ [gidesan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-07-27 09:13 UTC, merged