ENG-1353: FE - Change the widget config screen
entando/app-builder pull request #864
Opened 2020-10-09 20:20 UTC by gReis89

This is a workaround to disable the widgets config screens. As we can have many different configs, accordingly to the widget needs, the best approach would create a `readOnly` state for each widget we support, but keeping this standard would be very difficult.

So what I did was:

- creating a JS code that goes over any `["input","select","button","textarea"']` elements and set a disabled prop on it, but it won't cover all cases, as we have some elements being render after a fetch, or elements that doesn't are HTML inputs.
- disabling Cancel and Save button.
- added an invisible layer over the form, making it impossible for the users to trigger anything.

2020-10-09 20:20 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **greis89**

If they are not already assigned, you can assign the PR to them by writing `/assign @greis89` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["greis89"]} -->

2020-10-12 07:01 UTC, gidesan requested changes

2020-10-12 07:01 UTC, gidesan commented on src/ui/widgets/config/WidgetConfigPage.js
> +    defaultMessage: 'NaUnable to load widget configurationme',
```suggestion
    defaultMessage: 'Unable to load widget configuration',
```

2020-10-13 14:12 UTC, entando-jx commented
@gReis89: The following test **failed**, say `/retest` to rerun them all:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
pr-build | 48bf731dcf51fd26bc6f3ca05fd409522199dbdb | [link]() | `/test this`



<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2020-10-14 07:17 UTC, gidesan requested changes

2020-10-14 07:17 UTC, gidesan commented on sass/pages/config/PageConfigPage.scss
> +    background-color: rgba(0,0,0,.1); // sass-lint:disable-line variable-for-property
why not follow the linter here? not a big deal to add a variable, I guess

2020-10-14 07:17 UTC, gidesan commented on src/ui/widgets/config/WidgetConfigPage.js
> +  const saveButton = wrapper.querySelectorAll('[class*=save]')[0];
why direct DOM manipulation here?

2020-10-14 12:54 UTC, gidesan commented on src/ui/widgets/config/WidgetConfigPage.js
> +  const saveButton = wrapper.querySelectorAll('[class*=save]')[0];
after a short conversation, it's caused by some technical debt we have to solve

2020-10-14 12:55 UTC, gidesan approved these changes

2020-10-14 12:55 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/entando/app-builder/pull/864#pullrequestreview-508313388" title="Approved">gidesan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)~~ [gidesan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-14 12:55 UTC, merged