ENG-1253 implement tutorial
entando/app-builder pull request #870
Opened 2020-10-16 16:12 UTC by ichalagashvili

2020-10-16 16:13 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ichalagashvili**

If they are not already assigned, you can assign the PR to them by writing `/assign @ichalagashvili` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["ichalagashvili"]} -->

2020-10-19 07:20 UTC, jeffgo10 requested changes
only 1 comment from me but hopefully others can also review this since this is a massive PR x.x

2020-10-19 07:47 UTC, ichalagashvili commented on src/state/store.js
> +  composeParams.push(window.__REDUX_DEVTOOLS_EXTENSION__({trace: true, traceLimit: 25}));
yes but I can remove it, it was added because I wanted to trace something during debugging :) Forgot to remove..

2020-10-19 07:57 UTC, jeffgo10 commented on src/state/store.js
> +  composeParams.push(window.__REDUX_DEVTOOLS_EXTENSION__({trace: true, traceLimit: 25}));
okay. I think, because for production purposes, we'll have to remove it. but its good to know there's this option though

2020-10-20 11:14 UTC, jeffgo10 approved these changes
looks good

2020-10-20 11:14 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/entando/app-builder/pull/870#pullrequestreview-512594525" title="Approved">jeffgo10</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)~~ [jeffgo10]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-10-20 11:14 UTC, merged