ENG-1402 implement incremental name and code feature
entando/app-builder pull request #906
Opened 2020-11-05 15:44 UTC by ichalagashvili

2020-11-05 15:44 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **ichalagashvili**

If they are not already assigned, you can assign the PR to them by writing `/assign @ichalagashvili` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["ichalagashvili"]} -->

2020-11-05 16:38 UTC, gidesan requested changes

2020-11-05 16:38 UTC, gidesan commented on src/ui/pages/add/PagesAddFormContainer.js
> +export const getNextIncremetalPropertyName = (pages, property, keyword, extraChar) => {
can you please make it more functional?

2020-11-06 10:23 UTC, gidesan commented on src/ui/pages/add/PagesAddFormContainer.js
> +export const getNextIncremetalPropertyName = (pages, property, keyword, extraChar) => {
I'll made some commits to show up what I mean (and also something to improve test readability)

2020-11-06 17:53 UTC, gidesan approved these changes

2020-11-06 17:53 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/entando/app-builder/pull/906#pullrequestreview-525371911" title="Approved">gidesan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)~~ [gidesan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-11-06 18:05 UTC, merged