ENG-1482: adding new displayAttributes flag
entando/app-builder pull request #936
Opened 2020-11-20 21:20 UTC by gReis89

this is blocked by: https://jira.entando.org/browse/ENG-1521

2020-11-20 21:20 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **greis89**

If they are not already assigned, you can assign the PR to them by writing `/assign @greis89` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["greis89"]} -->

2020-12-14 14:50 UTC, gidesan requested changes

2020-12-14 14:50 UTC, gidesan commented on src/locales/it.js
> +    'user.myProfile.displayAttributes': 'Visualizzare gli attributi',
```suggestion
    'user.myProfile.displayAttributes': 'Visualizza attributi',
```

2020-12-15 07:37 UTC, gidesan approved these changes

2020-12-15 07:37 UTC, entando-jx commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/entando/app-builder/pull/936#pullrequestreview-552173573" title="Approved">gidesan</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=entando%2Fapp-builder).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/entando/app-builder/blob/master/OWNERS)~~ [gidesan]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2020-12-15 07:48 UTC, merged